//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flover_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int Id_Photo { get; set; }
        public int Id_Client { get; set; }
        public string Path { get; set; }
        public byte[] Image1 { get; set; }
    
        public virtual Сlients Сlients { get; set; }
    }
}
