//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flover_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id_payment { get; set; }
        public int Id_basket { get; set; }
        public int Id_delivery_type { get; set; }
        public Nullable<int> Id_self_call { get; set; }
        public Nullable<int> Id_delivery { get; set; }
        public System.DateTime Date_of_registration { get; set; }
        public System.DateTime Order_term { get; set; }
        public int Price_payment { get; set; }
        public int Stage_of_work { get; set; }
    
        public virtual Basket Basket { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Delivery_type Delivery_type { get; set; }
        public virtual Self_call Self_call { get; set; }
    }
}
