//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flover_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Otchestvo { get; set; }
        public int Floor { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Login { get; set; }
        public int Password { get; set; }
        public int Role { get; set; }
    
        public virtual Floor Floor1 { get; set; }
        public virtual Role Role1 { get; set; }
    }
}
