//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flover_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сlients
    {
        public int Id_clients { get; set; }
        public int id_user { get; set; }
        public string Telefon { get; set; }
        public string email { get; set; }
        public string image { get; set; }
        public int points { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
